about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

api/urls.py
from django.urls import path

from .views import (FavoritesView, ShoppingListView, SubscriptionView,
                    ingredients)

urlpatterns = [
    path('v1/ingredients/', ingredients),
    path('v1/favorites/', FavoritesView.as_view()),
    path('v1/favorites/<int:recipe_id>/', FavoritesView.as_view()),
    path('v1/subscriptions/', SubscriptionView.as_view()),
    path('v1/subscriptions/<int:author_id>/', SubscriptionView.as_view()),
    path('v1/purchases/', ShoppingListView.as_view()),
    path('v1/purchases/<int:recipe_id>/', ShoppingListView.as_view()),

]

foodgramsite/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'recipes.views.page_not_found'  # noqa
handler500 = 'recipes.views.server_error'  # noqa

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('recipes.urls'))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    {% block static %}
    {% endblock %}
</head>
<body class="body">
{% include 'nav.html' %}
{% block content %}
    <!-- Содержимое страницы -->
{% endblock content %}
{% include 'footer.html' %}
{% block js %}
{% endblock %}
</body>
</html>

templates/footer.html
<footer class="footer">
    <div class="footer__container container">
        <a href="{% url 'index' %}" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="{% url 'about:author' %}" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="{% url 'about:tech' %}" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}
{% block title %}Рецепты{% endblock %}
{% block static %}

    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}

{% block content %}
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">Рецепты</h1>
            {% include 'recipes/tags.html' %}
        </div>
        <div class="card-list">
            {% for recipe in page %}
                {% include 'recipes/recipe.html' %}
            {% endfor %}
        </div>
        {% include 'paginator.html' with items=page paginator=paginator %}
    </main>
{% endblock %}

{% block js %}
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/CardList.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'indexAuth.js' %}"></script>
{% endblock %}

templates/nav.html
{% load custom_filters %}
<header class="header">
    <nav class="nav">
        <div class="nav__container container">
            {% with current_url=request.resolver_match.url_name %}
                {% if user.is_authenticated %}
                    <ul class="nav__items list">
                        <li class="nav__item {% if 'index' in current_url or 'recipe_view' in current_url or 'profile' in current_url %}nav__item_active{% endif %}">
                            <a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
                        <li class="nav__item {% if 'subscription' in current_url %}nav__item_active{% endif %}"><a
                                href="{% url 'subscription' %}" class="nav__link link">Мои подписки</a></li>
                        <li class="nav__item {% if 'new_recipe' in current_url %}nav__item_active{% endif %}"><a
                                href="{% url 'new_recipe' %}" class="nav__link link">Создать рецепт</a></li>
                        <li class="nav__item {% if 'favorite_recipe' in current_url %}nav__item_active{% endif %}"><a
                                href="{% url 'favorite_recipe' %}" class="nav__link link">Избранное</a></li>
                        <li class="nav__item {% if 'shopping' in current_url %}nav__item_active{% endif %}"><a
                                href="{% url 'shopping_list' %}" class="nav__link link">Список покупок</a> <span
                                class="badge badge_style_blue nav__badge"
                                id="counter">{{ request|shopping_count }}</span></li>
                    </ul>
                    <ul class="nav__items list">
                        <li class="nav__item"><a href="{% url 'profile' username=user.username %}"
                                                 class="nav__link link">{{ user.username }}</a></li>
                        <li class="nav__item {% if 'password_change' in current_url %}nav__item_active{% endif %}"><a
                                href="{% url 'password_change' %}" class="nav__link link">Изменить
                            пароль</a></li>
                        <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link">Выход</a></li>
                    </ul>
                {% else %}
                    <ul class="nav__items list">
                        <li class="nav__item {% if 'index' in current_url or 'recipe_view' in current_url or 'profile' in current_url %}nav__item_active{% endif %}">
                            <a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
                        <li class="nav__item {% if 'shopping' in current_url %}nav__item_active{% endif %}"><a
                                href="{% url 'shopping_list' %}" class="nav__link link">Список покупок <span
                                class="badge badge_style_blue nav__badge"
                                id="counter">{{ request|shopping_count }}</span></a>
                        </li>
                    </ul>
                    <ul class="nav__items list">
                        <li class="nav__item"><a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
                        <li class="nav__item"><a href="{% url 'signup' %}" class="button button_style_blue">Создать
                            аккаунт</a>
                        </li>
                    </ul>
                {% endif %}
            {% endwith %}
        </div>
    </nav>
</header>

templates/paginator.html
<nav class="pagination" aria-label="Search results pages">
    <ul class="pagination__container">
        {% load custom_filters %}
        {% if paginator.num_pages > 1 %}

            {% if items.has_previous %}
                <li class="pagination__item"><a class="pagination__link link"
                                                href="?{{ request|change_page_url:items.previous_page_number }}"><span
                        class="icon-left"></span></a>
                </li>
            {% else %}
                <li class="pagination__item"><a class="pagination__link link" tabindex="-1"
                                                aria-disabled="true"><span class="icon-left"></span></a></li>
            {% endif %}

            {% for i in paginator.page_range %}
                {% if items.number == i %}
                    <li class="pagination__item pagination__item_active"><span
                            class="pagination__link link">{{ i }} </span>
                    </li>
                {% else %}
                    <li class="pagination__item"><a class="pagination__link link"
                                                    href="?{{ request|change_page_url:i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if items.has_next %}
                <li class="pagination__item"><a class="pagination__link link"
                                                href="?{{ request|change_page_url:items.next_page_number }}"><span
                        class="icon-right"></span></a>
                </li>
            {% else %}
                <li class="pagination__item"><a class="pagination__link link" tabindex="-1"
                                                aria-disabled="true"><span class="icon-right"></span></a></li>
            {% endif %}
        {% endif %}
    </ul>
</nav>