api/urls.py
from django.urls import path

from .views import (FavoritesView, ShoppingListView, SubscriptionView,
                    ingredients)

urlpatterns = [
    path('v1/ingredients/', ingredients),
    path('v1/favorites/', FavoritesView.as_view()),
    path('v1/favorites/<int:recipe_id>/', FavoritesView.as_view()),
    path('v1/subscriptions/', SubscriptionView.as_view()),
    path('v1/subscriptions/<int:author_id>/', SubscriptionView.as_view()),
    path('v1/purchases/', ShoppingListView.as_view()),
    path('v1/purchases/<int:recipe_id>/', ShoppingListView.as_view()),

]

foodgramsite/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'recipes.views.page_not_found'  # noqa
handler500 = 'recipes.views.server_error'  # noqa

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('recipes.urls'))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('404/', views.page_not_found, name='404'),
    path('500/', views.server_error, name='500'),
    path('new/', views.new_recipe, name='new_recipe'),
    path('favorite/', views.favorite_recipe, name='favorite_recipe'),
    path('subscription/', views.subscriptions_index,
         name='subscription'),
    path('shopping/', views.shopping_list, name='shopping_list'),
    path('shopping/<int:recipe_id>/', views.delete_purchase,
         name='delete_purchase'),
    path('shopping/save/', views.save_shopping_list,
         name='save_shopping_list'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/<int:recipe_id>/', views.recipe_view, name='recipe_view'),
    path('<username>/<int:recipe_id>/edit/', views.recipe_edit,
         name='recipe_edit'),
    path('<username>/<int:recipe_id>/delete/', views.recipe_delete,
         name='recipe_delete')
]

recipes/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.db import models

User = get_user_model()


class Ingredient(models.Model):
    title = models.CharField(max_length=255, verbose_name='ingredient title')
    dimension = models.CharField(max_length=64,
                                 verbose_name='ingredient dimension')

    def __str__(self):
        return f'{self.pk} - {self.title} - {self.dimension}'


class Tag(models.Model):
    title = models.CharField(max_length=50, verbose_name='tag title')
    slug = models.SlugField(max_length=50, verbose_name='tag slug',
                            unique=True)
    color = models.SlugField(verbose_name='tag color')

    def __str__(self):
        return f'{self.title}'


class RecipeManager(models.Manager):

    @staticmethod
    def tag_filter(tags):
        if tags:
            return Recipe.objects.filter(tags__slug__in=tags).order_by(
                '-pub_date').distinct()
        else:
            return Recipe.objects.order_by('-pub_date').all()


class Recipe(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='author_recipes')
    title = models.CharField(max_length=255, verbose_name='recipe title')
    image = models.ImageField(upload_to='recipe/', verbose_name='recipe image')
    description = models.TextField(verbose_name='recipe description')
    ingredients = models.ManyToManyField(Ingredient,
                                         through='RecipeIngredient',
                                         blank=True)
    tags = models.ManyToManyField(Tag, related_name='recipe_tag', blank=True)
    cooking_time = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        verbose_name='recipe cooking time')
    pub_date = models.DateTimeField(verbose_name='date published',
                                    auto_now_add=True,
                                    db_index=True)

    objects = RecipeManager()

    def __str__(self):
        return f'{self.pk} - {self.title} - {self.author}'


class RecipeIngredient(models.Model):
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE,
                                   related_name='ingredient_amount')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE,
                               related_name='recipe_amount')
    amount = models.PositiveIntegerField(validators=[MinValueValidator(1)])


class FavoriteRecipeManager(models.Manager):

    @staticmethod
    def favorite_recipe(user, tags):
        favorite = FavoriteRecipe.objects.filter(user=user).all()
        recipes_id = favorite.values_list('recipe', flat=True)
        favorite_list = Recipe.objects.tag_filter(tags).filter(
            pk__in=recipes_id).order_by('-pub_date')
        return favorite_list


class FavoriteRecipe(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='users_favorite')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE,
                               related_name='favorite_recipes')

    objects = FavoriteRecipeManager()

    def __str__(self):
        return f'{self.pk} - {self.user} - {self.recipe}'


class SubscriptionManager(models.Manager):

    @staticmethod
    def subscriptions(user):
        sub_obj = Subscription.objects.filter(user=user)
        author_id = sub_obj.values_list('author', flat=True)
        subscriptions_list = User.objects.filter(pk__in=author_id)
        return subscriptions_list


class Subscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='follower')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='following')

    objects = SubscriptionManager()

    def __str__(self):
        return f'{self.pk} - {self.user} - {self.author}'


class ShoppingListManager(models.Manager):

    @staticmethod
    def shopping_cart(user):
        shop_obj = ShoppingList.objects.filter(user=user)
        recipes_id = shop_obj.values_list('recipe', flat=True)
        cart = Recipe.objects.filter(pk__in=recipes_id)
        return cart


class ShoppingList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, )
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, )
    objects = ShoppingListManager()

    def __str__(self):
        return f'{self.pk} - {self.user} - {self.recipe}'

recipes/forms.py
from django.forms import (ModelForm)

from .models import Ingredient, Recipe


class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        fields = ('title', 'cooking_time', 'description', 'image',
                  'tags', 'ingredients')

    def clean(self):
        ing_added = False
        ing_in_db, amount = True, True
        for key in self.data.keys():

            if 'nameIngredient' in key:
                ing_added = True
                if not Ingredient.objects.filter(
                        title=self.data[key]).exists():
                    ing_in_db = False

            if 'valueIngredient' in key:
                if int(self.data[key]) <= 0:
                    amount = False

        if not amount:
            self.add_error('ingredients',
                           'Количесвто ингредиентов должно быть больше 0')

        if not ing_in_db:
            self.add_error('ingredients', 'Выберите ингредиент из списка')

        if not ing_added:
            self.add_error('ingredients',
                           'Добавьте ингредиенты к совему рецепту')

recipes/views.py
import logging
import sys

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import RecipeForm
from .models import (FavoriteRecipe, Ingredient, Recipe, RecipeIngredient,
                     ShoppingList, Subscription, User)
from .utils import get_ingredients, save_to_file

FORMAT = '[%(asctime)s] {%(pathname)s:%(lineno)d - %(funcName)s()} ' \
         '%(levelname)s - %(message)s'
logging.basicConfig(stream=sys.stdout, format=FORMAT)
logger = logging.getLogger(__name__)


def index(request):
    tags = request.GET.getlist('tag')
    recipe_list = Recipe.objects.tag_filter(tags)
    paginator = Paginator(recipe_list, settings.RECIPES_ON_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'index.html',
                  {'page': page, 'paginator': paginator})


@login_required
def new_recipe(request):
    form = RecipeForm(request.POST or None, files=request.FILES or None)
    context = {'form': form}
    if request.method != 'POST':
        return render(request, 'recipes/new_recipe.html', context)
    else:
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.save()
            form.save_m2m()
            ingredients = get_ingredients(request)
            for title, amount in ingredients.items():
                ingredient = get_object_or_404(Ingredient, title=title)
                recipe_ing = RecipeIngredient(recipe=recipe,
                                              ingredient=ingredient,
                                              amount=amount)
                recipe_ing.save()
            return redirect('index')
    return render(request, 'recipes/new_recipe.html', {'form': form})


@login_required
def recipe_edit(request, username, recipe_id):
    author = get_object_or_404(User, username=username)
    recipe = get_object_or_404(author.author_recipes, pk=recipe_id)
    if author != request.user:
        return redirect('recipe_view', username, recipe_id)
    else:
        form = RecipeForm(request.POST or None, files=request.FILES or None,
                          instance=recipe)
        if request.method == 'POST':
            if form.is_valid():
                form.save()
                ingredients = get_ingredients(request)
                for title, amount in ingredients.items():
                    ingredient = get_object_or_404(Ingredient, title=title)
                    recipe_ing = RecipeIngredient(recipe=recipe,
                                                  ingredient=ingredient,
                                                  amount=amount)
                    recipe_ing.save()
                return redirect('recipe_view', username, recipe_id)
        return render(request, 'recipes/new_recipe.html',
                      {'form': form, 'recipe': recipe})


@login_required
def recipe_delete(request, username, recipe_id):
    author = get_object_or_404(User, username=username)
    recipe = get_object_or_404(author.author_recipes, pk=recipe_id)
    if author != request.user:
        return redirect('recipe_view', username, recipe_id)
    else:
        recipe.delete()
    return redirect('index')


def profile(request, username):
    tags = request.GET.getlist('tag')
    author = get_object_or_404(User, username=username)
    post_list = Recipe.objects.tag_filter(tags).filter(author=author)
    paginator = Paginator(post_list, settings.RECIPES_ON_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'recipes/profile.html',
                  {'author': author, 'page': page, 'paginator': paginator})


def recipe_view(request, username, recipe_id):
    author = get_object_or_404(User, username=username)
    recipe = get_object_or_404(author.author_recipes, pk=recipe_id)
    return render(request, 'recipes/single_page.html',
                  {'author': author, 'recipe': recipe})


@login_required
def favorite_recipe(request):
    tags = request.GET.getlist('tag')
    favorite_list = FavoriteRecipe.objects.favorite_recipe(request.user, tags)
    paginator = Paginator(favorite_list, settings.RECIPES_ON_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    if not page:
        return render(request, 'recipes/custom_page.html')
    return render(request, 'recipes/favorite.html',
                  {'page': page, 'paginator': paginator})


@login_required
def subscriptions_index(request):
    subscriptions_list = Subscription.objects.subscriptions(user=request.user)
    paginator = Paginator(subscriptions_list, settings.RECIPES_ON_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    if not page:
        return render(request, 'recipes/custom_page.html')
    return render(request, 'recipes/subscription.html',
                  {'page': page, 'paginator': paginator})


def shopping_list(request):
    if request.user.is_authenticated:
        recipes = ShoppingList.objects.shopping_cart(user=request.user)
    else:
        try:
            recipes = Recipe.objects.filter(
                pk__in=request.session[settings.PURCHASE_SESSION_ID])
        except Exception as e:
            logger.error(str(e))
            return render(request, 'recipes/custom_page.html')
    if not recipes:
        return render(request, 'recipes/custom_page.html')
    return render(request, 'recipes/shopping_list.html', {'recipes': recipes})


def delete_purchase(request, recipe_id):
    if request.user.is_authenticated:
        recipe = get_object_or_404(Recipe, pk=recipe_id)
        purchase = get_object_or_404(ShoppingList, user=request.user,
                                     recipe=recipe)
        purchase.delete()
    else:
        try:
            request.session[settings.PURCHASE_SESSION_ID].remove(
                str(recipe_id))
            request.session.save()
        except Exception as e:
            logger.error(str(e))
    return redirect('shopping_list')


def save_shopping_list(request):
    if request.user.is_authenticated:
        recipes = ShoppingList.objects.shopping_cart(user=request.user)
    else:
        try:
            recipes = Recipe.objects.filter(
                pk__in=request.session[settings.PURCHASE_SESSION_ID])
        except Exception as e:
            logger.error(str(e))
            return render(request, 'recipes/custom_page.html')
    if recipes:
        return save_to_file(recipes)
    else:
        return render(request, 'recipes/custom_page.html')


def page_not_found(request, exception):
    return render(request, 'misc/404.html', {'path': request.path},
                  status=404)


def server_error(request):
    return render(request, 'misc/500.html', status=500)

recipes/templates/new_recipe.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Создание рецепта</title>
    <link rel="stylesheet" href="{% static 'pages/form.css' %}">
</head>
<body class="body">
<header class="header">
    <nav class="nav">
        <div class="nav__container container">
            <ul class="nav__items list">
                <li class="nav__item"><a href="#" class="nav__link link">Рецепты</a></li>
                <li class="nav__item"><a href="#" class="nav__link link">Мои подписки</a></li>
                <li class="nav__item"><a href="#" class="nav__link link">Создать рецепт</a></li>
                <li class="nav__item"><a href="#" class="nav__link link">Избранное</a></li>
                <li class="nav__item"><a href="#" class="nav__link link">Список покупок</a> <span
                        class="badge badge_style_blue nav__badge" id="counter"></span></li>

            </ul>
            <ul class="nav__items list">
                <li class="nav__item"><a href="#" class="nav__link link">Изменить пароль</a></li>
                <li class="nav__item"><a href="#" class="nav__link link">Выход</a></li>
            </ul>
        </div>
    </nav>
</header>
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">Создание рецепта</h1>
    </div>
    <div class="form-container">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form__group">
                <label for="id_name" class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    {#                    <input type="text" id="id_title" name="title" class="form__input">#}
                    {{ form.title }}
                    {% if form.title.errors %}
                        <span class="form__error">{{ form.title.errors }}</span>
                    {% endif %}
                    {#                    <span class="form__error"></span>#}
                </div>
            </div>
            <div class="form__group">
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="tags">
                        {% for tag in form.tags %}
                            <div class="tags__item">
                                {{ tag.tag }}
                                <label for="{{ tag.id_for_label }}" class="tags__label">{{ tag.choice_label }}</label>
                            </div>
                        {% endfor %}
                        {#                        <div class="tags__item">#}
                        {#                            <input type="checkbox" name="breakfast" id="id_breakfast"#}
                        {#                                   class="tags__checkbox tags__checkbox_style_orange">#}
                        {#                            <label for="id_breakfast" class="tags__label">Завтрак</label>#}
                        {#                        </div>#}
                        {#                        <div class="tags__item">#}
                        {#                            <input type="checkbox" name="lunch" id="id_lunch"#}
                        {#                                   class="tags__checkbox tags__checkbox_style_green" checked>#}
                        {#                            <label for="id_lunch" class="tags__label">Обед</label>#}
                        {#                        </div>#}
                        {#                        <div class="tags__item">#}
                        {#                            <input type="checkbox" name="dinner" id="id_dinner"#}
                        {#                                   class="tags__checkbox tags__checkbox_style_purple" checked>#}
                        {#                            <label for="id_dinner" class="tags__label">Ужин</label>#}
                        {#                        </div>#}
                    </div>
                    {% if form.tags.errors %}
                        <span class="form__error">{{ form.tags.errors }}</span>
                    {% endif %}
                    {#                    <span class="form__error"></span>#}
                </div>
            </div>

            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                    </div>
                    <div class="form__field-group-ingredientes-container">

                    </div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    {% if form.ingredients.errors %}
                        <span class="form__error">{{ form.ingredients.errors }}</span>
                    {% endif %}
                    {#                    <span class="form__error"></span>#}
                </div>
            </div>

            <div class="form__group">
                <label for="id_time" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    <input type="number" id="id_time" name="cooking_time" class="form__input"
                           value="{{ form.cooking_time_time.initial }}" min="0" required="">
                    <label for="id_time" class="form__label">минут</label>
                    {#                    <input type="text" id="id_cooking_time" name="cooking_time" class="form__input">#}
                    {#                    <label for="id_cooking_time" class="form__label">минут</label>#}
                    {% if form.cooking_time.errors %}
                        <span class="form__error">{{ form.cooking_time.errors }}</span>
                    {% endif %}
                    {#                    <span class="form__error"></span>#}
                </div>
            </div>
            <div class="form__group">
                <label for="id_description" class="form__label">Описание</label>
                <div class="form__field-group">
                    {% if form.description.initial == 'None' %}
                        <textarea name="description" id="id_description" rows="8" class="form__textarea"></textarea>
                    {% else %}
                        <textarea name="description" id="id_description" rows="8"
                                  class="form__textarea">{{ form.description.initial }}</textarea>
                    {% endif %}
                    {#                    <textarea name="description" id="id_description" rows="8" class="form__textarea"></textarea>#}
                    {% if form.description.errors %}
                        <span class="form__error">{{ form.description.errors }}</span>
                    {% endif %}
                    {#                    <span class="form__error"></span>#}
                </div>
            </div>
            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                    {#                    <input type="file" name="image" id="id_file">#}
                    {{ form.image }}
                    {% if form.image.errors %}
                        <span class="form__error">{{ form.image.errors }}</span>
                    {% endif %}
                    {#                    <span class="form__error"></span>#}
                </div>
            </div>
            <div class="form__footer">
                <button class="button button_style_blue">Создать рецепт</button>
            </div>
        </form>
    </div>


</main>
<footer class="footer">
    <div class="footer__container container">
        <a href="#" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="#" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="#" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>
<script src="{% static '/js/config/config.js' %}"></script>
<script src="{% static '/js/components/Header.js' %}"></script>
<script src="{% static '/js/utils/debouncing.js' %}"></script>
<script src="{% static '/js/api/Api.js' %}"></script>
<script src="{% static 'formRecipe.js' %}"></script>
</body>
</html>